name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update versions from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Updating to version: $VERSION"

          # Update pyproject.toml
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml

          # Update Cargo.toml package version only
          python3 -c "
          import re
          with open('Cargo.toml', 'r') as f:
              content = f.read()
          content = re.sub(
              r'(\[package\][^\[]*version = \")[^\"]+', 
              r'\g<1>${VERSION}',
              content,
              count=1
          )
          with open('Cargo.toml', 'w') as f:
              f.write(content)
          "

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Python wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          command: build
          args: --release
          sccache: "true"
          manylinux: auto

      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
